// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfficeBuddy.Api.Data;

#nullable disable

namespace OfficeBuddy.Api.Data.Migrations
{
    [DbContext(typeof(OfficeBuddyDbContext))]
    partial class OfficeBuddyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OfficeBuddy.Api.Data.ChannelOffice", b =>
                {
                    b.Property<string>("ChannelId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.HasKey("ChannelId");

                    b.HasIndex("OfficeId");

                    b.ToTable("ChannelOffices");
                });

            modelBuilder.Entity("OfficeBuddy.Api.Data.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("OfficeBuddy.Api.Data.Person", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("HomeOfficeId")
                        .HasColumnType("int");

                    b.HasKey("Oid");

                    b.HasIndex("HomeOfficeId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("OfficeBuddy.Api.Data.WorkplaceEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<Guid>("PersonOid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId", "Date");

                    b.HasIndex("PersonOid", "Date")
                        .IsUnique();

                    b.ToTable("WorkplaceEntries");
                });

            modelBuilder.Entity("OfficeBuddy.Api.Data.ChannelOffice", b =>
                {
                    b.HasOne("OfficeBuddy.Api.Data.Office", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("OfficeBuddy.Api.Data.Person", b =>
                {
                    b.HasOne("OfficeBuddy.Api.Data.Office", "HomeOffice")
                        .WithMany()
                        .HasForeignKey("HomeOfficeId");

                    b.Navigation("HomeOffice");
                });

            modelBuilder.Entity("OfficeBuddy.Api.Data.WorkplaceEntry", b =>
                {
                    b.HasOne("OfficeBuddy.Api.Data.Office", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OfficeBuddy.Api.Data.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonOid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");

                    b.Navigation("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
